"""Silver layer data transformation.

This file was generated by `polster add-asset`. Implement your transform() function
to process bronze data and write it to the silver layer.
"""

from __future__ import annotations

from datetime import datetime

import polars as pl

try:
    # Try relative imports (when run as module through Dagster)
    from .storage import read_parquet_latest, write_parquet
except ImportError:
    # Fall back to absolute imports (when run directly)
    import sys
    import os

    # Add src directory to path for absolute imports
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    from core.storage import read_parquet_latest, write_parquet


def transform() -> str:
    """Transform bronze data and write to silver layer.

    Returns:
        str: Path to the written parquet file.
    """
    # TODO: Uncomment and modify this example implementation with your actual data transformation logic
    #
    # # Read latest bronze data
    # df = read_parquet_latest("bronze", "bronze_{{ASSET_NAME}}_")
    #
    # # Apply transformations (example: clean data types)
    # cleaned = df.with_columns(
    #     pl.col("created_at").cast(pl.Datetime),
    #     pl.col("value").cast(pl.Float64).round(2),
    # )
    #
    # # Add transformation metadata
    # cleaned = cleaned.with_columns(
    #     pl.lit(datetime.utcnow().isoformat()).alias("transformed_at")
    # )
    #
    # # Write with timestamp
    # timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    # return write_parquet(cleaned, "silver", f"silver_{{ASSET_NAME}}_{timestamp}.parquet")
    #
    # Note: Uncomment the above code and modify it for your use case

    pass  # TODO: Replace with your implementation and remove this pass statement


if __name__ == "__main__":
    transform()
