"""Bronze layer data extraction.

This file was generated by `polster add-asset`. Implement your extract() function
to process data and write it to the bronze layer.
"""

from __future__ import annotations

from datetime import datetime

import polars as pl

try:
    # Try relative imports (when run as module through Dagster)
    from .storage import write_parquet
except ImportError:
    # Fall back to absolute imports (when run directly)
    import sys
    import os

    # Add src directory to path for absolute imports
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
    from core.storage import write_parquet


def extract() -> str:
    """Extract data and write to bronze layer.

    Returns:
        str: Path to the written parquet file.

    Example:
        # Create a simple DataFrame for testing
        df = pl.DataFrame({
            "id": [1, 2, 3],
            "name": ["Alice", "Bob", "Charlie"],
            "value": [10.5, 20.3, 15.7],
            "created_at": ["2024-01-01", "2024-01-02", "2024-01-03"]
        })

        # Add metadata
        df = df.with_columns(
            pl.lit(datetime.utcnow().isoformat()).alias("fetched_at")
        )

        # Write with timestamp
        timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
        return write_parquet(df, "bronze", f"bronze_{{ASSET_NAME}}_{timestamp}.parquet")
    """
    # TODO: Implement your data extraction logic here

    # Example code - uncomment to test:
    # df = pl.DataFrame({
    #     "id": [1, 2, 3],
    #     "name": ["Alice", "Bob", "Charlie"],
    #     "value": [10.5, 20.3, 15.7],
    #     "created_at": ["2024-01-01", "2024-01-02", "2024-01-03"]
    # })
    #
    # df = df.with_columns(
    #     pl.lit(datetime.utcnow().isoformat()).alias("fetched_at")
    # )
    #
    # timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    # return write_parquet(df, "bronze", f"bronze_{{ASSET_NAME}}_{timestamp}.parquet")

    raise NotImplementedError("Implement the extract() function")
