"""Gold layer data aggregation.

This file was generated by `polster add-asset`. Implement your aggregate() function
to process silver data and write it to the gold layer.
"""

from __future__ import annotations

from datetime import datetime

import polars as pl

try:
    # Try relative imports (when run as module through Dagster)
    from .storage import read_parquet_latest, write_parquet
except ImportError:
    # Fall back to absolute imports (when run directly)
    import sys
    import os

    # Add src directory to path for absolute imports
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    from core.storage import read_parquet_latest, write_parquet


def aggregate() -> str:
    """Aggregate silver data and write to gold layer.

    Returns:
        str: Path to the written parquet file.
    """
    # TODO: Uncomment and modify this example implementation with your actual data aggregation logic
    #
    # # Read latest silver data
    # df = read_parquet_latest("silver", "silver_{{ASSET_NAME}}_")
    #
    # # Apply aggregation (example: group by categories)
    # result = df.group_by("category").agg(
    #     total_value=pl.col("value").sum(),
    #     record_count=pl.len(),
    # )
    #
    # # Add aggregation metadata
    # result = result.with_columns(
    #     pl.lit(datetime.utcnow().isoformat()).alias("aggregated_at")
    # )
    #
    # # Write with timestamp
    # timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    # return write_parquet(result, "gold", f"gold_{{ASSET_NAME}}_{timestamp}.parquet")
    #
    # Note: Uncomment the above code and modify it for your use case

    pass  # TODO: Replace with your implementation and remove this pass statement


if __name__ == "__main__":
    aggregate()
