"""Gold asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset, AutomationCondition

try:
    # Try relative imports (when run as module through Dagster)
    from ...core.gold_{{ASSET_NAME}} import aggregate
    from ..utils import create_output_with_metadata
except ImportError:
    # Fall back to absolute imports (when run directly)
    import sys
    import os

    # Add src directory to path for absolute imports
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
    from core.gold_{{ASSET_NAME}} import aggregate
    from orchestration.utils import create_output_with_metadata


@asset(
    group_name="gold",
    description="Gold asset for {{ASSET_NAME}}",
    compute_kind="polars",
    automation_condition=AutomationCondition.eager(),
    deps=["run_silver_{{ASSET_NAME}}"],
)
def run_gold_{{ASSET_NAME}}():
    """Run gold aggregation for {{ASSET_NAME}}."""
    gold_path = aggregate()
    return create_output_with_metadata(gold_path)