"""Bronze asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset

from ...core.bronze_{{ASSET_NAME}} import extract
from ..utils import create_output_with_metadata


@asset(
    group_name="bronze",
    description="Bronze asset for {{ASSET_NAME}}",
    compute_kind="polars",
)
def run_bronze_{{ASSET_NAME}}():
    """Run bronze extraction for {{ASSET_NAME}}."""
    bronze_path = extract()
    return create_output_with_metadata(bronze_path)