"""Bronze asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset

try:
    # Try relative imports (when run as module through Dagster)
    from ...core.bronze_{{ASSET_NAME}} import extract
    from ..utils import create_output_with_metadata
except ImportError:
    # Fall back to absolute imports (when run directly)
    import sys
    import os

    # Add src directory to path for absolute imports
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
    from core.bronze_{{ASSET_NAME}} import extract
    from orchestration.utils import create_output_with_metadata


@asset(
    group_name="bronze",
    description="Bronze asset for {{ASSET_NAME}}",
    compute_kind="polars",
)
def run_bronze_{{ASSET_NAME}}():
    """Run bronze extraction for {{ASSET_NAME}}."""
    bronze_path = extract()
    return create_output_with_metadata(bronze_path)