"""Gold asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset

from ...core.gold_{{ASSET_NAME}} import aggregate
from ..utils import create_output_with_metadata


@asset(
    group_name="gold",
    description="Gold asset for {{ASSET_NAME}}",
    compute_kind="polars",
)
def run_gold_{{ASSET_NAME}}():
    """Run gold aggregation for {{ASSET_NAME}}."""
    gold_path = aggregate()
    return create_output_with_metadata(gold_path)