"""Silver asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset, AutomationCondition

from core.silver_{{ASSET_NAME}} import transform
from orchestration.utils import create_output_with_metadata


@asset(
    group_name="silver",
    description="Silver asset for {{ASSET_NAME}}",
    compute_kind="polars",
    automation_condition=AutomationCondition.eager(),
    deps=["run_bronze_{{ASSET_NAME}}"],
)
def run_silver_{{ASSET_NAME}}():
    """Run silver transformation for {{ASSET_NAME}}."""
    silver_path = transform()
    return create_output_with_metadata(silver_path)