# Polster CI/CD Pipeline for GitHub Actions
# This workflow automates data materialization and commits changes back to the repository

name: Polster Data Pipeline

# Trigger on push to master
on:
  push:
    branches:
      - master

  # Scheduled runs (UTC!)
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

  # Allow manual trigger
  workflow_dispatch:

jobs:
  materialize:
    runs-on: ubuntu-latest

    steps:
    # 0. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # 1. FORCE latest master (critical for scheduled runs)
    - name: Force latest master
      run: |
        echo "Forcing workspace to latest origin/master"
        git fetch origin master
        git checkout master || git checkout -b master
        git reset --hard origin/master

        echo "Running commit:"
        git log -1 --oneline

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install uv
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    # 4. Create venv + install dependencies
    - name: Create venv and install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        uv sync

    # 5. Run Polster materialization
    - name: Run run_polster.py
      run: |
        source .venv/bin/activate
        python run_polster.py

    # 6. Commit and push changes (if any)
    - name: Commit and push changes
      run: |
        git config user.email "pipeline@github-actions.local"
        git config user.name "GitHub Actions Pipeline"

        git status
        git add data/ .dagster/

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated commit from pipeline [skip ci]"

          # Force push to avoid merge conflicts
          git push origin master --force
        fi